[package]
name = "ruttle"
version = "0.1.0"
authors = ["shohi <oshohi@gmail.com>"]

[dependencies]
serde = "^1.0.27"
# json = "^0.11.13"
serde_json = "^1.0.9"
serde_derive = "^1.0.27"
toml = "^0.4.5"
try_opt = "^0.1.1"

rusoto_core = "^0.30.0"
rusoto_ec2 = "^0.30.0"
rusoto_s3 = "^0.30.0"